spring:
    application:
        name: MultipleMongoConnections

# URL parameters explanation:
#   w=majority (write concern)     : requests acknowledgement that write operations have propagated to
#                                    the majority of data-bearing voting members.
#   readPreference                 : omitted per the mongodb manual.  Primary is the default, and as
#                                    the manual states, any other mode may return stale data.
#   ssl=true                       : ensures that the connection is secured by SSL.
#   authSource=admin               : uses the "admin" database to look up credentials.  The default is
#                                    the database specified in the URI and, in our case, those databases
#                                    do not contain the credentials.
#   authMechanism=SCRAM-SHA-1      : Specifies to use the SCRAM-SHA-1 auth mechanism when authenticating
#                                    the connection.  This uses the SHA-1 hash algorithm for the
#                                    password.
#   appName=${app.name}            : Specifies a custom app name, which appears in the output of the
#                                    currentOp command, and in the system.profile.appName field in the
#                                    database profiler output.
#   tlsAllowInvalidHostnames=true  : Specifies that the ssl certificate does not need to match the host
#                                    name. Used for docker.
# mongodb:
#     uri: 'mongodb://
#   {{username}}:{{password}}
#   @{{hosts}}
#   /{{database}}
#   ?w=majority
#   &tls=true
#   &authSource=admin
#   &authMechanism=SCRAM-SHA-1
#   &appName=${spring.application.name}
#   &tlsAllowInvalidHostnames=true'
